### PR TITLE
pipeline : datalake

### PR DESCRIPTION
**Pull request by ThomasByr**
- MinIO bucket
- "objects"

### CODE REVIEW

**Comment by m7415** [comment]
Everything seems to be good !

**Review by mrkaby90 — DISMISSED** [review]
🥜

**Review by m7415 — APPROVED** [review]
Yup, I didn't read...

**Review by mrkaby90 — APPROVED** [review]
🥜🥜🥜🥜🥜🥜🥜🥜🥜🥜🥜🥜🥜🥜🥜🥜🥜🥜🥜🥜🥜🥜🥜🥜🥜🥜🥜🥜🥜🥜🥜🥜

**Pull request merged**
